### ISSUE TITLE
crash when /voice

### ISSUE THREAD

**Issue by ghost** [kappa-maintainer/NotEnoughKeys#1]
https://mclo.gs/bJ4cy5d

**Comment by ghost** [comment]
don't crash when I second use this command.but nek just crash the game when I get into the mainmenu.
https://mclo.gs/WZiPqqC

**Comment by kappa-maintainer** [comment]
Try the [pre-release](https://github.com/kappa-maintainer/NotEnoughKeys/releases/tag/0.1.2) for the first crash, as for the second one, try deleting all configs including options.txt

**Comment by ghost** [comment]
ok,I will try it later

**Comment by ghost** [comment]
It's fine now.By the way release the new version with https://github.com/kappa-maintainer/NotEnoughKeys/pull/2

**Comment by ghost** [comment]
@kappa-maintainer after deleting all the configs related to keys,I successfully enter the game but crash at the second time again.

**Comment by kappa-maintainer** [comment]
Crash report?

**Comment by ghost** [comment]
草，我不小心把文件恢复了
重新测试一下

**Comment by ghost** [comment]
@kappa-maintainer 我以为没事了，结果又炸了https://mclo.gs/ovFVgfq

**Comment by kappa-maintainer** [comment]
你这给我整不会了
是不是没装其他模组，我试试

**Comment by ghost** [comment]
纯净有问题吗，我这带的有点杂

**Comment by ghost** [comment]
我一开始以为是default option的问题，干了还是出问题。其他跟按键有关的就controlling，按键精灵和你新做的那个修复模组

**Comment by kappa-maintainer** [comment]
按键精灵是哪位

**Comment by kappa-maintainer** [comment]
草，怎么Keyboard Wizard是这翻译
我这试不出来，我看改改代码能不能修

**Comment by kappa-maintainer** [comment]
试试这个
https://github.com/kappa-maintainer/NotEnoughKeys/releases/tag/0.1.3

**Comment by ghost** [comment]
今天没时间了，明天试

**Comment by ghost** [comment]
现在没问题了，顺带提一嘴，这模组是怎么搞出这么大的文件体积的（）

**Comment by kappa-maintainer** [comment]
语音识别库
顺带一提你那翻译连key都打错两个
